# Generated by Django 4.1.4 on 2023-01-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='descritption',
            new_name='description',
        ),
    ]
